### ISSUE TITLE
[Bug]: Failing Structured Output Extraction with Guidance Pydantic Program

### ISSUE THREAD

**Issue by ghbacct** [run-llama/llama_index#9914]
### Bug Description

Several breaking changes were introduced in PR https://github.com/run-llama/llama_index/pull/9830 which intends to upgrade a dependency from `guidance==0.0.64` to `guidance==0.1.10`. 

1. When following [the example from the documentation](https://docs.llamaindex.ai/en/stable/examples/output_parsing/guidance_pydantic_program.html), the following line of code throws an exception:
`output = program(movie_name="The Shining")`, since the signature of the `program` function has been changed to require two new arguments `tools_str` and `query_str`. 

2. Assigning empty string values e.g. `output = program(movie_name="The Shining", tools_str='', query_str='')` results in a parsing exception. This seems to be related to the call on `pydantic_to_guidance_output_template_markdown` call being removed in the same PR.

Seems that functionality for `GuidancePydanticProgram` is now broken in `v0.9.27`? Any workarounds?

PS: Thank you for the initiative to upgrade the guidance library, and thank you for your help with fixing this issue.

### Version

0.9.27

### Steps to Reproduce

Run documentation example:
https://docs.llamaindex.ai/en/stable/examples/output_parsing/guidance_pydantic_program.html

### Relevant Logs/Tracbacks

```shell
The First Exception:

{
	"name": "TypeError",
	"message": "GuidancePydanticProgram.program() missing 2 required positional arguments: 'tools_str' and 'query_str'",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 44
     31     songs: List[Song]
     34 program = GuidancePydanticProgram(
     35     output_cls=Album,
     36     prompt_template_str=(
   (...)
     41     verbose=True,
     42 )
---> 44 output = program(movie_name=\"The Shining\") #, tools_str='', query_str='')
     46 display(output)

File ~/Development/My Project/.venv/lib/python3.11/site-packages/llama_index/program/guidance_program.py:102, in GuidancePydanticProgram.__call__(self, *args, **kwargs)
     97 def __call__(
     98     self,
     99     *args: Any,
    100     **kwargs: Any,
    101 ) -> BaseModel:
--> 102     executed_program = self._guidance_program(**kwargs)
    103     response = str(executed_program)
    105     return parse_pydantic_from_guidance_program(
    106         response=response, cls=self._output_cls
    107     )

TypeError: GuidancePydanticProgram.program() missing 2 required positional arguments: 'tools_str' and 'query_str'"
}
```

The Second Exception:
- Output prior to exception:
```
user
Generate an example album, with an artist and a list of songs. Using the movie 'The Shining' as inspiration
assistant
Album Artist: Echoes of the Overlook

Album Title: Labyrinth of Solitude

Album Tracklist:

1
```
- Exception:
```
{
	"name": "OutputParserException",
	"message": "Failed to parse pydantic object from guidance program. Probably the LLM failed to produce data with right json schema",
	"stack": "---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
File ~/Development/My Project/.venv/lib/python3.11/site-packages/llama_index/prompts/guidance_utils.py:146, in parse_pydantic_from_guidance_program(response, cls, verbose)
    145     json_dict = parse_json_markdown(output)
--> 146     sub_questions = cls.parse_obj(json_dict)
    147 except Exception as e:

File ~/Development/My Project/.venv/lib/python3.11/site-packages/typing_extensions.py:2499, in deprecated.__call__.<locals>.wrapper(*args, **kwargs)
   2498 warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
-> 2499 return arg(*args, **kwargs)

File ~/Development/My Project/.venv/lib/python3.11/site-packages/pydantic/main.py:1027, in BaseModel.parse_obj(cls, obj)
   1026 warnings.warn('The `parse_obj` method is deprecated; use `model_validate` instead.', DeprecationWarning)
-> 1027 return cls.model_validate(obj)

File ~/Development/My Project/.venv/lib/python3.11/site-packages/pydantic/main.py:503, in BaseModel.model_validate(cls, obj, strict, from_attributes, context)
    502 __tracebackhide__ = True
--> 503 return cls.__pydantic_validator__.validate_python(
    504     obj, strict=strict, from_attributes=from_attributes, context=context
    505 )

ValidationError: 1 validation error for Album
  Input should be a valid dictionary or instance of Album [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type

The above exception was the direct cause of the following exception:

OutputParserException                     Traceback (most recent call last)
Cell In[2], line 44
     31     songs: List[Song]
     34 program = GuidancePydanticProgram(
     35     output_cls=Album,
     36     prompt_template_str=(
   (...)
     41     verbose=True,
     42 )
---> 44 output = program(movie_name=\"The Shining\", tools_str='', query_str='')
     46 display(output)

File ~/Development/My Project/.venv/lib/python3.11/site-packages/llama_index/program/guidance_program.py:105, in GuidancePydanticProgram.__call__(self, *args, **kwargs)
    102 executed_program = self._guidance_program(**kwargs)
    103 response = str(executed_program)
--> 105 return parse_pydantic_from_guidance_program(
    106     response=response, cls=self._output_cls
    107 )

File ~/Development/My Project/.venv/lib/python3.11/site-packages/llama_index/prompts/guidance_utils.py:148, in parse_pydantic_from_guidance_program(response, cls, verbose)
    146     sub_questions = cls.parse_obj(json_dict)
    147 except Exception as e:
--> 148     raise OutputParserException(
    149         \"Failed to parse pydantic object from guidance program\"
    150         \". Probably the LLM failed to produce data with right json schema\"
    151     ) from e
    152 return sub_questions

OutputParserException: Failed to parse pydantic object from guidance program. Probably the LLM failed to produce data with right json schema"
}
```
```

**Comment by ghbacct** [comment]
@logan-markewich @amindadgar FYI

**Comment by logan-markewich** [comment]
@ghbacct no workarounds. I kind of trusted the contributor to test this 😅 Will try to take a look if I get time

**Comment by amindadgar** [comment]
I guess the examples needed an update. I'll try to update them on the weekend (Or sooner if I find some time).

**Comment by amindadgar** [comment]
Hey, I looked over it through the weekend and I saw there needed some updates to be applied. The reason for the error is, for now, it's just using the default template of `SubQuestionList` and it cannot produce the data with the given class structure. I'll try to make another PR over the next weekend.
