### ISSUE TITLE
[Bug]: Cannot import OpensearchVectorClient

### ISSUE THREAD

**Issue by kaiserfr** [run-llama/llama_index#10653]
### Bug Description

After upgrading to 0.10.1 I cannot import OpensearchVectorClient any more.

According to the docs it should be imported like "_**from llama_index.core.vector_stores import OpensearchVectorClient**_"
(see: https://docs.llamaindex.ai/en/stable/examples/vector_stores/OpensearchDemo.html#opensearch-vector-store)

When I try I get an import error.
I currently use the following module versions:

    "llama-index==0.10.1",
    "llama-index-agent-openai==0.1.1",
    "llama-index-core==0.10.1",
    "llama-index-embeddings-openai==0.1.1",
    "llama-index-legacy==0.9.48",
    "llama-index-llms-openai==0.1.1",
    "llama-index-multi-modal-llms-openai==0.1.1",
    "llama-index-program-openai==0.1.1",
    "llama-index-question-gen-openai==0.1.1",
    "llama-index-readers-elasticsearch>=0.1.1",
    "llama-index-readers-file==0.1.1",
    "llama-index-vector-stores-opensearch==0.1.1",

### Version

llama-index==0.10.1

### Steps to Reproduce

Import OpensearchVectorClient:

from llama_index.core.vector_stores import OpensearchVectorClient

### Relevant Logs/Tracbacks

```shell
ImportError: cannot import name 'OpensearchVectorClient' from 'llama_index.core.vector_stores' (/home/frank/kaiser/codecommit/ai/elasticpoc/.venv/lib/python3.10/site-packages/llama_index/core/vector_stores/__init__.py)
```

**Comment by logan-markewich** [comment]
@kaiserfr please ensure you have a fresh venv. Working from a fresh colab instance, the install + import works fine

```
pip install llama-index llama-index-vector-stores-opensearch
```

```
from llama_index.vector_stores.opensearch import OpenSearchVectorStore
```

https://colab.research.google.com/drive/1JK4mGVKpobJTeWw161la3pqhdOw7TIjH?usp=sharing

**Comment by kaiserfr** [comment]
Those modules are installed already (see bug description)

But I found another issue:

I was able to find this class in site-packages/llama_index/vector_stores/opensearch/base.py - so the class is there.
But in the **__init__.py** I find **__all__ = ["OpensearchVectorStore"]**.
Don't we need the OpenSearchVectorStore listed here too?

**Comment by kaiserfr** [comment]
Hi Logan,

I'm referring to OpensearchVector**Client**, not OpenSearchVector**Store**
This class is missing in the \_\_init\_\_.py file of site-packages/llama_index/vector_stores/opensearch

**Comment by Jotschi** [comment]
Correct import is:
```
from llama_index.vector_stores.opensearch.base import OpensearchVectorClient
```

**Comment by nerdai** [comment]
Yes, but I'm adding it back as a top-level import. This was the case before the v0.10 move. :)
