### ISSUE TITLE
[Question]: How to use a local model to embedding?

### ISSUE THREAD

**Issue by jiaoqianji** [run-llama/llama_index#12954]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I installed the latest version of llama-index three days ago and then tried to use a local model to index. but I encountered the following errors.

``` 
>>> from llama_index.embeddings.huggingface import HuggingFaceEmbedding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'llama_index.embeddings.huggingface'
>>> from llama_index.embeddings import HuggingFaceEmbedding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HuggingFaceEmbedding' from 'llama_index.embeddings' (unknown location)
```

After upgrading from v0.10.29 to v0.10.30, I then downgraded to v0.10.17, but neither version worked.
I downloaded all packages starting with 'llama_index' or 'llamaindex' and looked them up, but found only an 'openai' directory inside them.

![f37e17423827f8592698c8f05e72e7a](https://github.com/run-llama/llama_index/assets/103246345/b991d634-d21f-4638-a06e-38afea021e30)

**Comment by logan-markewich** [comment]
You have to install it

`pip install llama-index-embeddings-huggingface`

**Comment by jiaoqianji** [comment]
> You have to install it
> 
> `pip install llama-index-embeddings-huggingface`

thank you, my problem solved.
