### ISSUE TITLE
[Bug]: Cannot initialize RedisVectorStore with only redis_url since v0.5.1

### ISSUE THREAD

**Issue by dev-newvisibility** [run-llama/llama_index#18981]
### Bug Description

Since the version 0.5.1 of the `llama-index-vector-stores-redis` package I'm unable to initialize the RedisVectorStore by passing only the Redis URL. It fails with the following error:

```
  File "/home/dev/.local/lib/python3.12/site-packages/llama_index/vector_stores/redis/base.py", line 190, in __init__
    host=redis_client.connection_pool.connection_kwargs["host"],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connection_pool'
```

I think the bug was introduced with the PR #18675 . The following line does not correctly check whether the variable `redis_client` is `None`: https://github.com/run-llama/llama_index/blob/03b5dc9fab40bbac8a8624c578db97fab748d006/llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py#L185

The tests do not cover the case of a `RedisVectorStore` initialized with the `redis_url` argument only.

### Version

llama-index-vector-stores-redis==0.5.1

### Steps to Reproduce

Initialize the Redis vector store passing only the Redis URL instead of a client:

```python
vector_store = RedisVectorStore(redis_url="redis://localhost:6379")
```

### Relevant Logs/Tracbacks

```shell

```

**Comment by AstraBert** [comment]
Hey there @dev-newvisibility, I'll check this and let you know!
