### PR TITLE
Correcting Redis URL/Client handling

### LINKED ISSUE #18981: [Bug]: Cannot initialize RedisVectorStore with only redis_url since v0.5.1
### Bug Description

Since the version 0.5.1 of the `llama-index-vector-stores-redis` package I'm unable to initialize the RedisVectorStore by passing only the Redis URL. It fails with the following error:

```
  File "/home/dev/.local/lib/python3.12/site-packages/llama_index/vector_stores/redis/base.py", line 190, in __init__
    host=redis_client.connection_pool.connection_kwargs["host"],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connection_pool'
```

I think the bug was introduced with the PR #18675 . The following line does not correctly check whether the variable `redis_client` is `None`: https://github.com/run-llama/llama_index/blob/03b5dc9fab40bbac8a8624c578db97fab748d006/llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py#L185

The tests do not cover the case of a `RedisVectorStore` initialized with the `redis_url` argument only.

### Version

llama-index-vector-stores-redis==0.5.1

### Steps to Reproduce

Initialize the Redis vector store passing only the Redis URL instead of a client:

```python
vector_store = RedisVectorStore(redis_url="redis://localhost:6379")
```

### Relevant Logs/Tracbacks

```shell

```

### PR DESCRIPTION
**Pull request by AstraBert**
# Description

In `llama-index-vector-store-redis` v0.5.1 we incorrectly check for the `redis_client`, so that the `RedisVectorStore` object cannot be loaded simply from a URL anymore. With this PR, we correct the redis client handling so that the client is instatiated from the URL, if the `redis_client` itself is not passed.

Fixes #18981 

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [X] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [X] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [ ] I added new unit tests to cover this change
- [X] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I ran `uv run make format; uv run make lint` to appease the lint gods

### CODE REVIEW

File: llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py [hunk 1]
```diff
@@ -183,6 +183,11 @@ def __init__(
         )
         self._redis_client_async = redis_client_async
         if redis_client or redis_url:
+            if redis_url and not redis_client:
+                redis_client = Redis(
```
Comment (logan-markewich) [inline llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py]: We can use `Redis.from_url()` I think? Slightly safer

Comment (AstraBert) [reply llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py]: Yup :)
