### ISSUE TITLE
[Feature Request]: ChatMessage can not be found in 'llama_index.core.llms

### ISSUE THREAD

**Issue by abhi12121998** [run-llama/llama_index#10636]
### Feature Description

ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms'

**Comment by Jotschi** [comment]
I think I got the same issue. I think the import in `token_counting` has not yet been migrated to the new location.

```
  File "/home/jotschi/workspaces/rag/rag/llama-index-streamlit/venv/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py", line 6, in <module>
    from llama_index.core.llms import ChatMessage, MessageRole
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)
```

https://github.com/run-llama/llama_index/blob/c6dbd6ea806c19864c49dde7ee29176700ca1218/llama-index-core/llama_index/core/utilities/token_counting.py#L6

Should be: `llama_index.core.llms.base`

@abhi12121998 Did you encounter the same location?

**Comment by MakeCodeTasty** [comment]
using this example provided in the official Documentation.
```python

from llama_index.llms.openai import OpenAI

response = OpenAI().complete("Paul Graham is ")
print(response)

``` 
Getting the same error

```python
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)
```

**Comment by abhi12121998** [comment]
solved

**Comment by Jotschi** [comment]
@abhi12121998 It is better to share the solution instead of just writing "solved".

I was able to resolve the issue by recreating my env and reinstalling llama index from scratch.

**Comment by benbenz** [comment]
I am having the same issue with vLLM. I couldn't migrate to 10.0 or 10.1 (which seemed to solve the issue by looking at the code) because of incompatible packages. And the offending line is line 6 in this code:

https://github.com/run-llama/llama_index/blob/v0.9.48/llama_index/utilities/token_counting.py

This should be re-opened for older versions as long as there are issues with migrating to 10.x

**Comment by fsuarezj** [comment]
I have the same issue with llama-index 0.10.4.
From the official documentation: https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/usage_pattern.html

I'm getting:
ImportError: cannot import name 'PromptTemplate' from 'llama_index.core' (unknown location)

**Comment by JoseGHdz** [comment]
I am running into the same issue when calling anything that's not legacy. For example:

from llama_index.legacy.llms import OpenAI --> Works Fine
from llama_index.finetuning.callbacks import OpenAIFineTuningHandler --> Gives me error
from llama_index.core import Settings --> Does nothing

The error I have been getting is:
File "/opt/homebrew/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py", line 6, in <module>
    from llama_index.core.llms import ChatMessage, MessageRole
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)

I am on LlamaIndex 0.10.3. I've installed and uninstalled LlamaIndex multiple times and I have also made a new venv and so far nothing has worked. Help is appreciated.

**Comment by Jotschi** [comment]
@fsuarezj 

from llama_index.core.prompts import PromptTemplate

**Comment by IsisChameleon** [comment]
I had a similar problem with version 0.10.4 after upgrading from 0.9.36. I did uninstall llama_index (poetry remove llama_index in my case) then reinstalled it and it fixed the problem.

**Comment by dew-maris-hugeman** [comment]
Uninstall all of `llama_index` packages and reinstall again then it worked.

**Comment by qrospars** [comment]
> I had this issue yesterday, I was in 0.9.48 before the upgrade to 0.10.4.
> 
> What helped me was uninstalling all the llama-index packages: pip uninstall llama-index pip uninstall llama-index-legacy pip uninstall llama-index-agent-openai pip uninstall llama-index-core pip uninstall llama-index-embeddings-adapter pip uninstall llama-index-embeddings-openai pip uninstall llama-index-finetuning pip uninstall llama-index-llms-gradient pip uninstall llama-index-llms-openai pip uninstall llama-index-multi-modal-llms-openai pip uninstall llama-index-postprocessor-cohere-rerank pip uninstall llama-index-program-openai pip uninstall llama-index-question-gen-openai pip uninstall llama-index-readers-file
> 
> After this, I only ran: pip install llama-index
> 
> After I installed the llama-index package, my code worked again although I had to make changes on the libraries imported to my code by including core.
> 
> Before, I would call: from llama_index import VectorStoreIndex Now, I call: from llama_index.core import VectorStoreIndex
> 
> That's it. I hope this helps

I did that and it worked for me. Thanks @JoseGHdz :)

**Comment by fsuarezj** [comment]
Thanks @IsisChameleon @JoseGHdz @qrospars  It worked, now I'm upgrading my code to 0.10 :)

**Comment by urbanscribe** [comment]
when importing

    from llama_index.core.query_engine.retriever_query_engine import RetrieverQueryEngine

get a library internal import error
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (/usr/local/lib/python3.9/site-packages/llama_index/core/llms/__init__.py)


llama-index                              0.10.5
llama-index-agent-openai                 0.1.1
llama-index-core                         0.10.5
llama-index-embeddings-openai            0.1.1
llama-index-legacy                       0.9.48
llama-index-llms-openai                  0.1.1
llama-index-multi-modal-llms-openai      0.1.1
llama-index-program-openai               0.1.1
llama-index-question-gen-openai          0.1.1
llama-index-readers-file                 0.1.3

broken import
File "/usr/local/lib/python3.9/site-packages/llama_index/core/utilities/token_counting.py", line 6, in <module>
    from llama_index.core.llms import ChatMessage, MessageRole

**Comment by alikaz3mi** [comment]
Hi. This issue isn't solved in `0.10.6`

```python
../parschat_logic/adapters/llm_model.py:1: in <module>
    from llama_index.core.llms.mock import MockLLM
/home/ali/.local/lib/python3.10/site-packages/llama_index/core/llms/mock.py:9: in <module>
    from llama_index.core.callbacks import CallbackManager
/home/ali/.local/lib/python3.10/site-packages/llama_index/core/callbacks/__init__.py:4: in <module>
    from .token_counting import TokenCountingHandler
/home/ali/.local/lib/python3.10/site-packages/llama_index/core/callbacks/token_counting.py:6: in <module>
    from llama_index.core.utilities.token_counting import TokenCounter
/home/ali/.local/lib/python3.10/site-packages/llama_index/core/utilities/token_counting.py:6: in <module>
    from llama_index.core.llms import ChatMessage, MessageRole
E   ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)

Process finished with exit code 2
```

**Comment by wenziheng777** [comment]
> I had this issue yesterday, I was in 0.9.48 before the upgrade to 0.10.4.
> 
> What helped me was uninstalling all the llama-index packages: pip uninstall llama-index pip uninstall llama-index-legacy pip uninstall llama-index-agent-openai pip uninstall llama-index-core pip uninstall llama-index-embeddings-adapter pip uninstall llama-index-embeddings-openai pip uninstall llama-index-finetuning pip uninstall llama-index-llms-gradient pip uninstall llama-index-llms-openai pip uninstall llama-index-multi-modal-llms-openai pip uninstall llama-index-postprocessor-cohere-rerank pip uninstall llama-index-program-openai pip uninstall llama-index-question-gen-openai pip uninstall llama-index-readers-file
> 
> After this, I only ran: pip install llama-index
> 
> After I installed the llama-index package, my code worked again although I had to make changes on the libraries imported to my code by including core.
> 
> Before, I would call: from llama_index import VectorStoreIndex Now, I call: from llama_index.core import VectorStoreIndex
> 
> That's it. I hope this helps

I had the same situation and fixed the problem using the same method :)

**Comment by cmosguy** [comment]
I just installed `ragatouille` package and the second I did this and try to use:
```python
from ragatouille import RAGPretrainedModel
```
This error happens:
```sh
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' 
````
Do I really have to uninstall llama-index again?  This is weird.

**Comment by LaksLaksman** [comment]
use: from llama_index.core.base.llms.types import ( ChatMessage)

this is a common problem occurs when using llama index, I went through several similar problems. what you  can do is just go to the source code and search for the keywords, find actually where the function has been written. by this way you can identify the actual path to do the imports.

**Comment by LaksLaksman** [comment]
from llama_index.core.base.llms.types import (
    ChatMessage,
    ChatResponse,
    ChatResponseAsyncGen,
    ChatResponseGen,
    CompletionResponse,
    CompletionResponseAsyncGen,
    CompletionResponseGen,
    LLMMetadata,
    TextBlock,
)
