### ISSUE TITLE
[Bug]: ImportError: cannot import name 'ArgPackComponent' from 'llama_index.core.query_pipeline.components'

### ISSUE THREAD

**Issue by steve36871** [run-llama/llama_index#10791]
### Bug Description

It seems llama-index version 0.9.48 was unable to import name 'ArgPackComponent' from 'llama_index.core.query_pipeline.components'

I tried all versions of llama-index-core from pypi and none works. I want to avoid upgrading to 0.10.x due to some incompatibilities within my project. In the past I was able to use this llama-index version and I restored my 'poetry.lock' file to the last working version, but somehow the packages do not work together anymore. Any ideas?

### Version

0.9.48

### Steps to Reproduce

Run 'from llama_index.retrievers import QueryFusionRetriever'

**Comment by logan-markewich** [comment]
If you do have `llama-index==0.9.48` installed, the correct import is `from llama_index.query_pipeline import ArgPackComponent`

**Comment by yinheng-gh** [comment]
The same problem occurred after updating to 0.9.48, which was also present in poetry update. Downgrading to 0.9.40 (the version I previously used without any issues) did not solve the problem. The issue arises when calling deeper into the import of retrievers, rather than being caused by manually importing in my own code. Therefore, we cannot simply modify this import error in the source code of query_pipeline ourselves.

```   
from llama_index.retrievers import VectorIndexRetriever
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/retrievers/__init__.py", line 40, in <module>
    from llama_index.retrievers.router_retriever import RouterRetriever
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/retrievers/router_retriever.py", line 12, in <module>
    from llama_index.selectors.utils import get_selector_from_context
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/selectors/__init__.py", line 3, in <module>
    from llama_index.selectors.pydantic_selectors import (
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/selectors/pydantic_selectors.py", line 10, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/program/__init__.py", line 5, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/program/openai_program.py", line 4, in <module>
    from llama_index.agent.openai.utils import resolve_tool_choice
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/agent/__init__.py", line 2, in <module>
    from llama_index.agent.custom.pipeline_worker import QueryPipelineAgentWorker
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/agent/custom/pipeline_worker.py", line 27, in <module>
    from llama_index.query_pipeline.components.agent import (
  File "/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/query_pipeline/__init__.py", line 3, in <module>
    from llama_index.core.query_pipeline.components import (
ImportError: cannot import name 'ArgPackComponent' from 'llama_index.core.query_pipeline.components' (/Users/yinheng/Codes/ita/ita-api/.venv/lib/python3.10/site-packages/llama_index/core/query_pipeline/components/__init__.py)
```

**Comment by rmandrad** [comment]
I am getting exactly the same issue trying to run the llamaindex-cli rag ...

**Comment by logan-markewich** [comment]
I cannot patch a previous version. I can only say that I haven't seen this issue in v0.10.x

**Comment by amaboh** [comment]
I am facing the same issue presently after running this line of 
query_engine = index.as_query_engine()

% pip show llama-index
Name: llama-index
Version: 0.9.48

**Comment by logan-markewich** [comment]
This is fixed in newer versions. You'll need to downgrade further, or upgrade to v0.10.6
