### PR TITLE
Add OpensearchVectorClient to __init__

### LINKED ISSUE #10653: [Bug]: Cannot import OpensearchVectorClient
### Bug Description

After upgrading to 0.10.1 I cannot import OpensearchVectorClient any more.

According to the docs it should be imported like "_**from llama_index.core.vector_stores import OpensearchVectorClient**_"
(see: https://docs.llamaindex.ai/en/stable/examples/vector_stores/OpensearchDemo.html#opensearch-vector-store)

When I try I get an import error.
I currently use the following module versions:

    "llama-index==0.10.1",
    "llama-index-agent-openai==0.1.1",
    "llama-index-core==0.10.1",
    "llama-index-embeddings-openai==0.1.1",
    "llama-index-legacy==0.9.48",
    "llama-index-llms-openai==0.1.1",
    "llama-index-multi-modal-llms-openai==0.1.1",
    "llama-index-program-openai==0.1.1",
    "llama-index-question-gen-openai==0.1.1",
    "llama-index-readers-elasticsearch>=0.1.1",
    "llama-index-readers-file==0.1.1",
    "llama-index-vector-stores-opensearch==0.1.1",

### Version

llama-index==0.10.1

### Steps to Reproduce

Import OpensearchVectorClient:

from llama_index.core.vector_stores import OpensearchVectorClient

### Relevant Logs/Tracbacks

```shell
ImportError: cannot import name 'OpensearchVectorClient' from 'llama_index.core.vector_stores' (/home/frank/kaiser/codecommit/ai/elasticpoc/.venv/lib/python3.10/site-packages/llama_index/core/vector_stores/__init__.py)
```

### PR DESCRIPTION
**Pull request by nerdai**
# Description

- adds OpensearchVectorClient as top-level import for llama-index-vector-stores-opensearch package
- fixes broken imports in docs/examples/vector_stores/OpensearchDemo.ipynb
- publishes a patch for this package (now v0.1.2)
- adds CHANGELOG

Fixes #10653 #10658 

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
Changelogs! Forgot about those 😆

**Comment by nerdai** [comment]
> Changelogs! Forgot about those 😆

Hehe. We could do automate the addition of these to all of our 380+ packages. Or, we can just add it as we go along lol.
