### ISSUE TITLE
I keep getting this error "AttributeError: module 'llama_index' has no attribute '__version__'[Bug]: " when using LlamaIndex with Chainlit

### ISSUE THREAD

**Issue by Stephen-Echessa** [run-llama/llama_index#10917]
### Bug Description

I tried running chainlit with my llama index code today, which by the way is taking too long to run a query when I was testing on Jupyter Notebooks, and each time I run the command 'chainlit run app.py -w', I keep getting the error: "AttributeError: module 'llama_index' has no attribute '__version__' . I don't know what is causing this.

Here is my code:

      from llama_index.legacy.llms import LlamaCPP
      from llama_index.legacy.llms.llama_utils import messages_to_prompt, completion_to_prompt
      from llama_index.legacy import (
        SimpleDirectoryReader, 
        StorageContext, 
        ServiceContext,
        VectorStoreIndex, 
        load_index_from_storage
      )
      from llama_index.legacy.embeddings import HuggingFaceEmbedding
      from llama_index.legacy.node_parser import SimpleNodeParser
      from llama_index.legacy.vector_stores import WeaviateVectorStore
      from llama_index.legacy.callbacks.base import CallbackManager
      import chainlit as cl
      
      # Initialize the weaviate store
      vector_store = WeaviateVectorStore(url='http://localhost:8080')
      
      # Function to load index from storage
      @cl.cache # Allow to cache the function
      def load_context():
          try:
              # Rebuild storage index
              storage_context = StorageContext.from_defaults(vector_store=vector_store, callback_manager=CallbackManager([
                  cl.LlamaIndexCallbackHandler()
              ]))
              # Load index
              index = load_index_from_storage(storage_context=storage_context)
              
          except:
              # Storage not found, create a new one
              documents = SimpleDirectoryReader(
                  input_files=['./data/Reading 2 Text Analytics for Beginners using NLTK_240116_161801.pdf']
                  ).load_data()
              
              # Initialize model
              llm = LlamaCPP(
                  model_path='./model/dolphin-2.6-mistral-7b.Q4_K_M.gguf',
                  context_window=1600,
                  max_new_tokens=256,
                  verbose=False,
                  messages_to_prompt=messages_to_prompt,
                  completion_to_prompt=completion_to_prompt
              ) 
               
              # Call Embedding Transformer
              embedding_model = HuggingFaceEmbedding(model_name='BAAI/bge-small-en-v1.5')
              
              # Break text to chunks
              parser = SimpleNodeParser(chunk_size=1024, chunk_overlap=0)
              nodes = parser.get_nodes_from_documents(documents)
              nodes   
              
              system_prompt="""
                  You are a Q&A assistant. Your goal is to answer questions as
                  accurately as possible based on the instructions and context provided.
              """ 
              
              service_context = ServiceContext.from_defaults(llm=llm, 
                                                     embed_model=embedding_model, 
                                                     system_prompt=system_prompt,
                                                     callback_manager=CallbackManager([
                                                         cl.LlamaIndexCallbackHandler()
              ]))
              
              index = VectorStoreIndex(nodes,
                               service_context=service_context
              )
              index.storage_context.persist(vector_store_fname=vector_store)
           
          return index
      
      
      @cl.on_chat_start    
      async def start():
          index = load_context()
          query_engine = index.as_query_engine(
              streaming=True,
              vector_store_query_mode='hybrid',
              alpha=0.0
          )     
          
          await cl.Message(author='Assistant', content='Hello! How may I help you?').send()
          cl.user_session.set("query_engine", query_engine)
            
              
      @cl.on_message
      async def main(message: cl.Message):
          query_engine = cl.user_session.get('query_engine')
          response = await cl.make_async(query_engine.query)(message.content)
          
          response_message = cl.Message(content='')
          
          for token in response.response_gen:
              await response_message.stream_token(token=token)
          
          await response_message.send()

I would really appreciate it if someone could help me come up with a solution for this. My chainlit application opens up but it can't generate a response due to the error.

### Version

llama-index v0.10.5

### Steps to Reproduce

When trying to integrate the llama index code to your Chainlit application with the recent version of llamaindex which is v0.10.5.

### Relevant Logs/Tracbacks

```shell
File "/home/chescore/anaconda3/lib/python3.11/site-packages/chainlit/llama_index/__init__.py", line 3, in <module>
    if not check_module_version("llama_index", "0.8.3"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chescore/anaconda3/lib/python3.11/site-packages/chainlit/utils.py", line 87, in check_module_version
    return version.parse(module.__version__) >= version.parse(required_version)
                         ^^^^^^^^^^^^^^^^^^
AttributeError: module 'llama_index' has no attribute '__version__'
```

**Comment by logan-markewich** [comment]
In v0.10.x, it's not possible to define version there

Technically it would be at llama_index.core
__version__

So
a) I should add that attribute back
b) I'm guessing chainlit needs to be updated to work with v0.10.x

**Comment by Stephen-Echessa** [comment]
Sorry for the late reply. I am still using the latest version of chainlit and I am getting still this error. I can only assume that it is something that the developers of chainlit should look at.

**Comment by logan-markewich** [comment]
@Stephen-Echessa yes, chainlit should use `llama_index.core.__version__`

**Comment by Stephen-Echessa** [comment]
Thank you for the reply. Guess I'll just have to wait and maybe even give FastAPI a shot in the meantime.
