### ISSUE TITLE
[Bug]: OpenAI broken in 0.10.6

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#10982]
### Bug Description

I'm following the example provided in graph search engine. https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html

However, I cannot even run ``from llama_index.llms.openai import OpenAI`` because I'm encountering an error of ``ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)``

### Version

0.10.6

### Steps to Reproduce

%pip install llama-index-llms-azure-openai
%pip install llama-index-graph-stores-nebula
%pip install llama-index-llms-openai
%pip install llama-index-embeddings-azure-openai
pip install llama-index==0.10.6

### Code
import os

os.environ["OPENAI_API_KEY"] = "sk-"

import logging
import sys

logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output

from llama_index.llms.openai import OpenAI
from llama_index.core import Settings

Settings.llm = OpenAI(temperature=0, model="gpt-3.5-turbo")
Settings.chunk_size = 512

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 16
     10 logging.basicConfig(
     11     stream=sys.stdout, level=logging.INFO
     12 )  # logging.DEBUG for more verbose output
     15 # define LLM
---> 16 from llama_index.llms.openai import OpenAI
     17 from llama_index.core import Settings
     19 Settings.llm = OpenAI(temperature=0, model="gpt-3.5-turbo")

File /opt/homebrew/lib/python3.11/site-packages/llama_index/llms/openai/__init__.py:1
----> 1 from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
      3 __all__ = ["OpenAI", "Tokenizer", "SyncOpenAI", "AsyncOpenAI"]

File /opt/homebrew/lib/python3.11/site-packages/llama_index/llms/openai/base.py:28
     16 from llama_index.core.base.llms.types import (
     17     ChatMessage,
     18     ChatResponse,
   (...)
     25     MessageRole,
     26 )
     27 from llama_index.core.bridge.pydantic import Field, PrivateAttr
---> 28 from llama_index.core.callbacks import CallbackManager
     29 from llama_index.core.constants import (
     30     DEFAULT_TEMPERATURE,
     31 )
     32 from llama_index.core.llms.callbacks import (
     33     llm_chat_callback,
     34     llm_completion_callback,
     35 )

File /opt/homebrew/lib/python3.11/site-packages/llama_index/core/callbacks/__init__.py:4
      2 from .llama_debug import LlamaDebugHandler
      3 from .schema import CBEvent, CBEventType, EventPayload
----> 4 from .token_counting import TokenCountingHandler
      5 from .utils import trace_method
      7 __all__ = [
      8     "CallbackManager",
      9     "CBEvent",
   (...)
     14     "trace_method",
     15 ]

File /opt/homebrew/lib/python3.11/site-packages/llama_index/core/callbacks/token_counting.py:6
      4 from llama_index.core.callbacks.base_handler import BaseCallbackHandler
      5 from llama_index.core.callbacks.schema import CBEventType, EventPayload
----> 6 from llama_index.core.utilities.token_counting import TokenCounter
      7 from llama_index.core.utils import get_tokenizer
     10 @dataclass
     11 class TokenCountingEvent:

File /opt/homebrew/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py:6
      1 # Modified from:
      2 # https://github.com/nyno-ai/openai-token-counter
      4 from typing import Any, Callable, Dict, List, Optional
----> 6 from llama_index.core.llms import ChatMessage, MessageRole
      7 from llama_index.core.utils import get_tokenizer
     10 class TokenCounter:

ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)
```

**Comment by logan-markewich** [comment]
@mw19930312 please start from a fresh venv. Any remnants of the previous install will cause some issues due to the change to namespaced packages

In a new terminal
```
pip uninstall llama-index  # just to confirm its not installed globally
python -m venv venv
source venv/bin/activate
pip install llama-index ....
```

**Comment by juicesharp** [comment]
Same issue here, after migrate to 10.6 the issue persist in the new environment as well. `from .token_counting import TokenCountingHandler
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/core/callbacks/token_counting.py", line 6, in <module>
    from llama_index.core.utilities.token_counting import TokenCounter
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py", line 6, in <module>
    from llama_index.core.llms import ChatMessage, MessageRole
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)`

**Comment by logan-markewich** [comment]
@juicesharp try creating a new venv, as I described above :) Should help. For example, this all works in a fresh colab, which indicates just some env tweaking/setup is needed

**Comment by mw19930312** [comment]
@logan-markewich Creating a new venv works. Thanks!

**Comment by cmosguy** [comment]
I did a fresh install in my conda env and I am still seeing this error:

```sh
ImportError: cannot import name 'BasePromptTemplate' from partially initialized module 'llama_index.core.prompts' (most likely due to a circular import) (/opt/miniconda3/envs/proj/lib/python3.10/site-packages/llama_index/core/prompts/__init__.py)

```

**Comment by logan-markewich** [comment]
@cmosguy yea that's a slightly different issue. Update all llama-index-* packages you have installed and it should be working

**Comment by harshit0209** [comment]
I also had the same issue, got resolved by: `https://docs.llamaindex.ai/en/stable/getting_started/starter_example/`
<br>
Looks like there had been some change with updates
