### ISSUE TITLE
[Bug]: query engine `output_cls` no longer work with pydantic v2 after upgrade to llama-index v10

### ISSUE THREAD

**Issue by sasensi** [run-llama/llama_index#12243]
### Bug Description

Using a pydantic v2 data model as output class for the llama-index query engine no longer work after upgrade to v10.
The program fails with the following error:
```
AttributeError: 'BaseModel' object has no attribute 'model_dump'
```

### Version

0.10.23

### Steps to Reproduce

- setup a python `3.12` virtual environment
- install those packages:
```
llama-index==0.10.23
llama-index-embeddings-openai==0.1.6
llama-index-llms-openai==0.1.12
llama-index-program-openai==0.1.4
llama-index-vector-stores-postgres==0.1.3
python-dotenv==1.0.1
pydantic==2.6.3
```
- create an `.env` file containing `OPENAI_API_KEY=<YOUR_API_KEY>`
- run this script:
```python
from dotenv import load_dotenv
from llama_index.core import Document, VectorStoreIndex
from llama_index.llms.openai import OpenAI
from pydantic import BaseModel

load_dotenv()

class MyModel(BaseModel):
    """Data model for a content."""

    content: str

documents = [Document(text="A brief history of chocolate")]
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine(
    output_cls=MyModel,
    llm=OpenAI(model="gpt-3.5-turbo")
)

response = query_engine.query("What is it about ?")

print("content: ",response.content)
print("response type: ",type(response.response))
# `model_dump` method is available for pydantic v2 models but not for v1.
print("response dump: ",response.response.model_dump())
```
- you should see this error
```
AttributeError: 'BaseModel' object has no attribute 'model_dump'
```

---

Note that the same was working with llama-index version `0.9.47`:
- installing those packages:
```
llama-index==0.9.47
python-dotenv==1.0.1
pydantic~=2.6.3
```
- running this script (only import differ)
```python
from dotenv import load_dotenv
from llama_index import Document, VectorStoreIndex
from llama_index.llms import OpenAI
from pydantic import BaseModel

load_dotenv()

class MyModel(BaseModel):
    """Data model for a content."""

    content: str

documents = [Document(text="A brief history of chocolate")]
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine(
    output_cls=MyModel,
    llm=OpenAI(model="gpt-3.5-turbo")
)

response = query_engine.query("What is it about ?")

print("content: ",response.content)
print("response type: ",type(response.response))
# `model_dump` method is available for pydantic v2 models but not for v1.
print("response dump: ",response.response.model_dump())
```
- You get this output:
```
content:  A brief history of chocolate
response type:  <class '__main__.MyModel'>
response dump:  {'content': 'A brief history of chocolate'}
```

**Comment by logan-markewich** [comment]
Use the v1 compatibility layer 

`from pydantic.v1 import BaseModel`

Or import from llamaindex

`from llama_index.core.bridge.pydantic import BaseModel`

**Comment by sasensi** [comment]
> Use the v1 compatibility layer
> 
> `from pydantic.v1 import BaseModel`
> 
> Or import from llamaindex
> 
> `from llama_index.core.bridge.pydantic import BaseModel`

@logan-markewich, thank you for your quick reply, I already tried those and saw that this indeed solves the issue.  
The problem for me is that I'm relying on pydantic v2 models for the rest of my app and those were working fine with llama-index v9.  
This is why I was surprised that the same no longer works with v10.  
Is there a way to make v10 work with pydantic v2 models ?

**Comment by logan-markewich** [comment]
@sasensi tbh I'm surprised it worked before lol

There are some hacks ways to make this work, but tbh the entire library needs to be updated to ditch the v1 layer for full compatibility 

One hacky fix

```
class MyModel(BaseModel):
    """Data model for a content."""

    content: str
    
    def model_dump(self, *args, **kwargs):
        return self.dict(*args, **kwargs)
```

**Comment by sasensi** [comment]
@logan-markewich, ok, I understand, I'll then look forward to llama-index fully supporting pydantic v2 and implement some workarounds for my specific use cases in the meantime.  
Thank you again for your work and reactivity 👍
