### ISSUE TITLE
[Bug]: import error generated by SimpleDirectoryReader()

### ISSUE THREAD

**Issue by wb200** [run-llama/llama_index#10773]
### Bug Description

After upgrading to 0.10.4 SimpleDirectoryReader() generates an import error as it cannot find "DocxReader" in "llama_index.readers.file".

![image](https://github.com/run-llama/llama_index/assets/45331952/5fe5768a-32be-4871-80b1-19221de08f3b)

### Version

0.10.3

### Steps to Reproduce

import openai
import os
import llama_index.core.readers as readers

openai.api_key = os.environ['OPENAI_API_KEY']

source_dir_html = '/home/wb200/data/llm/doc/MLX_AU/test/html/'

reader = readers.SimpleDirectoryReader(input_dir=source_dir_html)
documents = reader.load_data()

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/wb200/anaconda3/envs/llm/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 21, in _try_loading_included_file_formats
    from llama_index.readers.file import (
ImportError: cannot import name 'DocxReader' from 'llama_index.readers.file' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wb200/python/LLM/test.py", line 13, in <module>
    documents = reader.load_data()
                ^^^^^^^^^^^^^^^^^^
  File "/home/wb200/anaconda3/envs/llm/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 396, in load_data
    SimpleDirectoryReader.load_file(
  File "/home/wb200/anaconda3/envs/llm/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 303, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wb200/anaconda3/envs/llm/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 35, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found
```

**Comment by wb200** [comment]
Btw the import work fine on its own ...

![image](https://github.com/run-llama/llama_index/assets/45331952/ec52763b-6a65-4d2c-96af-6bec18deb280)

**Comment by wb200** [comment]
Should it be an import as this: "from llama_index.readers.file.docs import DocxReader"??

**Comment by logan-markewich** [comment]
@wb200 can you try with a fresh venv?

For example, I do
```
python -m venv venv
source venv/bin/activate
pip install llama-index
```

And then it works for me

**Comment by jiyzhang** [comment]
> @dosu-bot
> 
> With 0.10.4 your imports have become very confusing. Shouldn't you move everything in "https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file" to "core/readers/..."?
> 
> Also, the import error occurs in llama-index code, not mine. The import in "llama_index/core/readers/file/base.py" cannot find DocxReader which is now in "https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py" ...

Same issue occurred in 0.10.5, confusing....

**Comment by wb200** [comment]
> @wb200 can you try with a fresh venv?
> 
> For example, I do
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install llama-index
> ```
> 
> And then it works for me

Haven't tried that yet as I'm used to conda env system. And it doesn't seem to work there.

**Comment by logan-markewich** [comment]
@jiyzhang please create a fresh venv and try again

**Comment by logan-markewich** [comment]
@wb200 I'm by no means a co da expert, but you should be able to do 

```
conda deactivate
conda create -n new_venv
conda activate new_venv
pip install -U llama-index
```

If llama-index was installed globally before in the base environment (a bad practice) you night need to uninstall it first 
```

**Comment by jiyzhang** [comment]
> @jiyzhang please create a fresh venv and try again

I created a new env with conda and didn't encounter this issue again. thanks

**Comment by datascientist** [comment]
> > @jiyzhang please create a fresh venv and try again
> 
> I created a new env with conda and didn't encounter this issue again. thanks

Same here

**Comment by damsdams1995** [comment]
`Traceback (most recent call last):
  File "/Users/admin/Desktop/physhcs_llm/chatbox.py", line 31, in <module>
    index = construct_index("docs")
  File "/Users/admin/Desktop/physhcs_llm/chatbox.py", line 13, in construct_index
    docs = SimpleDirectoryReader(directory_path).load_data()
  File "/Users/admin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/llama_index/core/readers/file/base.py", line 396, in load_data
    SimpleDirectoryReader.load_file(
  File "/Users/admin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/llama_index/core/readers/file/base.py", line 303, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
  File "/Users/admin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/llama_index/core/readers/file/base.py", line 35, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found` can some help me please

**Comment by damsdams1995** [comment]
I have already downloaded the llama-index-readers-file, same issue :)

**Comment by sglbl** [comment]
@damsdams1995 I fixed the issue with this:
```
pip3 uninstall llama-index
pip3 install llama-index --upgrade --no-cache-dir --force-reinstall
```

**Comment by schkovich** [comment]
> _🤖_
> 
> 
>     * [docs/getting_started/v0_10_0_migration.md](https://github.com/run-llama/llama_index/blob/main/docs/getting_started/v0_10_0_migration.md)
> 
>     * [llama_index/**init**.py](https://github.com/run-llama/llama_index/blob/main/llama_index/__init__.py)
> If you want to continue the conversation, start your reply with @dosu-bot.
@dosu-bot

The provided links are broken.

**Comment by HasnainKhanNiazi** [comment]
> @damsdams1995 I fixed the issue with this:
> 
> ```
> pip3 uninstall llama-index
> pip3 install llama-index --upgrade --no-cache-dir --force-reinstall
> ```

Thanks, this solved the issue without creating a new environment.
